"""Fixed input dimension evidence: size, count and unknown workspace entries.

No Core reader, YAML loader or limit check is implemented here. Inputs are built
from reviewed constants and the generated bytes are measured again against the
documented limits, so each fixture crosses exactly one dimension and no other.
"""
import json
from pathlib import Path
import subprocess
import tempfile

from jsonschema import Draft202012Validator, ValidationError

from .document_fixtures import DOCUMENT, REQ_PATH
from .harness import setup
from .initial_fixtures import CONFIGS, observe, compare_state

HERE = Path(__file__).resolve().parent
CONFIG_PATH = ".spec/bitz.yaml"
REQ2_PATH = ".spec/requirements/REQ-002.md"
TEST_PATH = "tests/test_req_001.py"
UNKNOWN_PATH = ".spec/notes.txt"
CONFIG = CONFIGS["SINGLE-001"]
# docs/03.詳細設計/00_共通契約/02_安全な入出力・互換性.md §4 resource上限.
CONFIG_LIMIT = 64 * 1024
SPEC_LIMIT = 1024 * 1024
FRONTMATTER_LIMIT = 32 * 1024
ITEM_LIMIT = 1000
LIMIT_CODE = "SPEC-INPUT-LIMIT-001"
COMMENT_LINE = "# 設定fileの64 KiB上限を超えるための固定コメント。\n"
PROSE_LINE = "この段落はSPEC Markdownの1 MiB上限を超えるための固定文である。\n"
NOTE_UNIT = "padding-"
TEST_FILE = b'raise RuntimeError("check must not execute this file")\n'
UNKNOWN_FILE = "SPECとして読み込まない検査用のmemoである。\n"
REQUIREMENT_2 = (
    "---\nid: REQ-002\ntitle: 追加の規範文\nstatus: approved\n---\n\n# REQ-002 追加の規範文\n\n"
    "## Intent\n\n配列上限の対象となる規範文を1件だけ提供する。\n\n## Acceptance Criteria\n\n"
    "- [REQ-002:AC-01] [ACTOR:TargetSystem] [ALWAYS] [MUST] [CONSTRAINT] 秘密情報を出力しない。\n\n"
    "## Verification\n\nCore実装後に確認する。現時点では未証明。\n")
# ID: (code, source path, source key, summary, status, 検査文書数, 検査句数, description)
CASES = {
    "SINGLE-078": (LIMIT_CODE, CONFIG_PATH, None, "設定fileが64 KiB上限を超過しました",
                   "failed", 0, 0, "設定fileの上限超過で読取りを続けない"),
    "SINGLE-079-01": (LIMIT_CODE, REQ_PATH, None, "SPEC Markdownが1 MiB上限を超過しました",
                      "failed", 0, 0, "SPEC Markdownの上限超過で文書を検査しない"),
    "SINGLE-079-02": (LIMIT_CODE, REQ_PATH, None, "Frontmatterが32 KiB上限を超過しました",
                      "failed", 0, 0, "Frontmatterの上限超過で文書を検査しない"),
    "SINGLE-080-01": (None, None, None, None,
                      "passed", 1, ITEM_LIMIT, "上限ちょうどの規範文と関係配列を遮断しない"),
    "SINGLE-080-02": (LIMIT_CODE, REQ_PATH, None, "1文書の規範文数が1,000上限を超過しました",
                      "failed", 0, 0, "規範文数の上限超過で文書を検査しない"),
    "SINGLE-080-03": (LIMIT_CODE, REQ_PATH, "tests[0].covers",
                      "1文書の関係・path配列の項目数が1,000上限を超過しました",
                      "failed", 1, 1, "配列項目数の上限超過で文書を検査しない"),
    "SINGLE-083": ("SPEC-WORKSPACE-UNKNOWN-001", UNKNOWN_PATH, None, ".spec/内の未知fileをSPECとして読みません",
                   "passed_with_warnings", 1, 1, ".spec/内の未知fileを警告しSPECとして読まない"),
}
# Which reviewed dimension each fixture is allowed to cross; everything else must stay inside.
CROSSED = {"SINGLE-078": {"config"}, "SINGLE-079-01": {"spec"}, "SINGLE-079-02": {"frontmatter"},
           "SINGLE-080-01": set(), "SINGLE-080-02": {"statements"}, "SINGLE-080-03": {"covers"},
           "SINGLE-083": set()}


def repeat(text, limit):
    """Smallest fixed repetition of text that alone passes the reviewed limit."""
    return text * (limit // len(text.encode()) + 2)


def oversized_config():
    return (CONFIG + repeat(COMMENT_LINE, CONFIG_LIMIT)).encode()


def oversized_spec():
    return (DOCUMENT + "\n" + repeat(PROSE_LINE, SPEC_LIMIT)).encode()


def oversized_frontmatter():
    note = 'x-note: "' + repeat(NOTE_UNIT, FRONTMATTER_LIMIT) + '"\n'
    return DOCUMENT.replace("status: approved\n---", "status: approved\n" + note + "---", 1).encode()


def statement(index):
    return (f"- [REQ-001:AC-{index:04d}] [ACTOR:TargetSystem] [ALWAYS] [MUST] [CONSTRAINT] "
            f"検査項目{index:04d}の秘密情報を出力しない。\n")


def covers_ids(count):
    return [f"REQ-001:AC-{index:04d}" for index in range(1, count + 1)]


def requirement(statements, covers):
    frontmatter = ("---\nid: REQ-001\ntitle: 上限の検査\nstatus: approved\ntests:\n"
                   f"  - path: {TEST_PATH}\n    covers:\n"
                   + "".join(f"      - {identifier}\n" for identifier in covers) + "---\n\n")
    body = ("# REQ-001 上限の検査\n\n## Intent\n\n入力寸法の上限を検査する。\n\n## Acceptance Criteria\n\n"
            + "".join(statement(index) for index in range(1, statements + 1))
            + "\n## Verification\n\nCore実装後に確認する。現時点では未証明。\n")
    return (frontmatter + body).encode()


def reviewed_inputs(identifier):
    inputs = {CONFIG_PATH: CONFIG.encode(), REQ_PATH: DOCUMENT.encode()}
    if identifier == "SINGLE-078":
        inputs[CONFIG_PATH] = oversized_config()
    elif identifier == "SINGLE-079-01":
        inputs[REQ_PATH] = oversized_spec()
    elif identifier == "SINGLE-079-02":
        inputs[REQ_PATH] = oversized_frontmatter()
    elif identifier == "SINGLE-080-01":
        inputs[REQ_PATH] = requirement(ITEM_LIMIT, covers_ids(ITEM_LIMIT))
        inputs[TEST_PATH] = TEST_FILE
    elif identifier == "SINGLE-080-02":
        inputs[REQ_PATH] = requirement(ITEM_LIMIT + 1, covers_ids(ITEM_LIMIT))
        inputs[TEST_PATH] = TEST_FILE
    elif identifier == "SINGLE-080-03":
        inputs[REQ_PATH] = requirement(ITEM_LIMIT, covers_ids(ITEM_LIMIT) + ["REQ-002:AC-01"])
        inputs[REQ2_PATH] = REQUIREMENT_2.encode()
        inputs[TEST_PATH] = TEST_FILE
    elif identifier == "SINGLE-083":
        inputs[UNKNOWN_PATH] = UNKNOWN_FILE.encode()
    return inputs


def frontmatter_size(document):
    parts = document.split(b"---\n", 2)
    if len(parts) != 3 or parts[0]:
        raise ValueError("document has no delimited Frontmatter")
    return len(parts[1])


def statement_count(document):
    return sum(1 for line in document.splitlines() if line.startswith(b"- [REQ-"))


def covers_count(document):
    return sum(1 for line in document.splitlines() if line.startswith(b"      - REQ-"))


def check_limits(identifier, inputs):
    """The fixed bytes, not the prose, must decide which limit a fixture crosses."""
    config, document = inputs[CONFIG_PATH], inputs[REQ_PATH]
    measured = {"config": len(config) > CONFIG_LIMIT, "spec": len(document) > SPEC_LIMIT,
                "frontmatter": frontmatter_size(document) > FRONTMATTER_LIMIT,
                "statements": statement_count(document) > ITEM_LIMIT,
                "covers": covers_count(document) > ITEM_LIMIT}
    crossed = {name for name, over in measured.items() if over}
    if crossed != CROSSED[identifier]:
        raise ValueError(f"input crosses {sorted(crossed)} instead of {sorted(CROSSED[identifier])}")
    if identifier.startswith("SINGLE-080") and (statement_count(document) < ITEM_LIMIT
                                                or covers_count(document) < ITEM_LIMIT):
        raise ValueError("boundary case must fill both reviewed limits")
    if identifier == "SINGLE-083":
        entry = Path(UNKNOWN_PATH)
        if UNKNOWN_PATH not in inputs or entry.parent.as_posix() != ".spec" or entry.suffix == ".md":
            raise ValueError("unknown-entry case needs a non-SPEC file directly under .spec/")


def reviewed_manifest(identifier):
    status = CASES[identifier][4]
    return {"fixtureId": identifier, "description": CASES[identifier][7],
            "setup": {"git": True, "baseCommit": {"message": "base", "paths": ["."]}, "operations": []},
            "invocation": {"runner": "bitz", "cwd": ".",
                           "argv": ["check", "--full", "--base", "HEAD", "--format", "json"], "env": {}},
            "expect": {"status": status, "exitCode": 1 if status == "failed" else 0, "stdout": "json",
                       "resultFile": "expected/check.json", "reportFileCount": 0}}


def reviewed_result(identifier):
    code, path, key, summary, status, documents, statements, _ = CASES[identifier]
    diagnostics = []
    if code is not None:
        source = {"kind": "file", "workspaceId": "root", "path": path}
        if key is not None:
            source["key"] = key
        diagnostics.append({"code": code, "severity": "warning" if status == "passed_with_warnings" else "error",
                            "resultStatus": status, "summary": summary, "source": source})
    return {"schemaVersion": "1.0", "operation": "check", "status": status, "scope": "full",
            "workspace": {"id": "root", "path": "."},
            "revision": {"base": "0" * 40, "commit": "0" * 40, "dirty": False},
            "checkedDocumentCount": documents, "checkedStatementCount": statements, "durationMs": 0,
            "diagnostics": diagnostics}


def validate(root=HERE, identifiers=None):
    errors, prepared = [], []
    validators = {name: Draft202012Validator(json.loads((root / f"{name}.schema.json").read_text()))
                  for name in ("manifest", "result", "side-effects")}
    for identifier in CASES:
        if identifiers is not None and identifier not in identifiers:
            continue
        fixture = root / "single" / identifier
        try:
            manifest = json.loads((fixture / "manifest.json").read_text())
            result = json.loads((fixture / "expected/check.json").read_text())
            effects = json.loads((fixture / "side-effects.json").read_text())
            for name, value in (("manifest", manifest), ("result", result), ("side-effects", effects)):
                validators[name].validate(value)
            if manifest != reviewed_manifest(identifier) or result != reviewed_result(identifier):
                raise ValueError("manifest or result differs from reviewed single condition")
            inputs = reviewed_inputs(identifier)
            check_limits(identifier, inputs)
            files = {p.relative_to(fixture / "repo").as_posix(): p
                     for p in (fixture / "repo").rglob("*") if p.is_file() or p.is_symlink()}
            if set(files) != set(inputs) or any(p.is_symlink() or p.read_bytes() != inputs[name]
                                                for name, p in files.items()):
                raise ValueError("input differs from the reviewed corpus")
            if effects["policy"] != "read-only" or effects["before"] != effects["after"]:
                raise ValueError("limit detection must not write files")
            previous = None
            with tempfile.TemporaryDirectory(prefix="bitz-input-limit-") as temporary:
                for run in range(2):
                    sandbox = Path(temporary) / str(run)
                    sandbox.mkdir()
                    repository = setup(fixture, manifest, sandbox / "repo")
                    external = {name: sandbox / name for name in ("home", "cache", "temporary")}
                    for path in external.values():
                        path.mkdir()
                    actual = observe(repository, external)
                    if compare_state(effects["before"], actual) or (previous is not None and previous != actual):
                        raise ValueError("isolated setup differs from fixed snapshot")
                    previous = actual
            prepared.append(identifier)
        except (OSError, ValueError, KeyError, TypeError, ValidationError, subprocess.SubprocessError) as error:
            errors.append(f"{identifier}: {str(error).split(chr(10))[0]}")
    return {"prepared": prepared, "setups_per_fixture": 2, "core_execution": "Not run",
            "status": "Passed" if not errors else "Failed", "errors": errors}
